import react from 'react';
import { StyleSheet } from 'react-native';

const ProfileStylesheet = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  scrollContainer: {
    paddingBottom: 120,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#14532d',
    paddingVertical: 30,
    paddingHorizontal: 20,
    marginBottom: 0,
  },
  avatarWrapper: {
    backgroundColor: '#388e3c',
    borderRadius: 55,
    padding: 4,
    elevation: 6,
    marginRight: 18,
  },
  avatar: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: '#388e3c',
    alignSelf: 'center',
    borderWidth: 3,
    borderColor: '#fff',
  },
  headerInfo: {
    flex: 1,
    justifyContent: 'center',
  },
  name: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 4,
    textShadowColor: '#0006',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  username: {
    fontSize: 16,
    color: '#c8e6c9',
    fontWeight: '600',
    textShadowColor: '#0004',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 1,
  },
  infoSection: {
    backgroundColor: '#fff',
    marginHorizontal: 20,
    marginTop: 18,
    borderRadius: 16,
    padding: 20,
    elevation: 2,
    marginBottom: 20,
  },
  infoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    paddingBottom: 6,
  },
  infoIcon: {
    marginRight: 8,
  },
  infoLabel: {
    fontWeight: 'bold',
    color: '#14532d',
    fontSize: 16,
    marginRight: 4,
  },
  infoValue: {
    fontSize: 16,
    color: '#333',
    flexShrink: 1,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#14532d',
    marginBottom: 10,
    marginLeft: 24,
    marginTop: 10,
  },
  loadingText: {
    textAlign: 'center',
    color: '#888',
    marginVertical: 20,
  },
  noPosts: {
    textAlign: 'center',
    color: '#888',
    marginVertical: 20,
  },
  postCard: {
    backgroundColor: '#fff',
    marginHorizontal: 20,
    marginBottom: 12,
    padding: 15,
    borderRadius: 8,
    elevation: 1,
  },
  postTitle: {
    fontWeight: 'bold',
    fontSize: 16,
    color: '#222',
  },
  postRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
  postImagePlaceholder: {
    width: 80,
    height: 80,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#222',
    backgroundColor: '#eee',
    marginRight: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  postInfo: {
    flex: 1,
    justifyContent: 'center',
  },
  postLabel: {
    fontSize: 15,
    color: '#388E3C',
    fontWeight: 'bold',
    marginBottom: 2,
  },
  postContent: {
    fontSize: 15,
    color: '#222',
  },
  tokenSection: {
    marginTop: 40,
    marginHorizontal: 20,
    backgroundColor: '#f9f9f9',
    borderRadius: 8,
    padding: 10,
    elevation: 0,
    marginBottom: 30,
  },
  tokenLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#888',
    marginBottom: 5,
  },
  tokenValue: {
    fontSize: 10,
    fontFamily: 'monospace',
    color: '#bbb',
    backgroundColor: '#f9f9f9',
    padding: 6,
    borderRadius: 5,
  },
  logoutButtonContainer: {
    position: 'absolute',
    bottom: 20,
    left: 0,
    right: 0,
    alignItems: 'center',
  },
  logoutButton: {
    backgroundColor: '#f44336',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 30,
    elevation: 5,
  },
  logoutText: {
    color: 'white',
    marginLeft: 8,
    fontWeight: 'bold',
    fontSize: 16,
  },
  map: {
    width: 250,
    height: 150,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#388e3c',
  },
});

export default ProfileStylesheet;